### ISSUE TITLE
Freckle timer no longer displays

### ISSUE THREAD

**Issue by mightymaxv2** [RobertDaleSmith/freckle-chrome-extension#3]
Error in error log: 

Refused to display 'https://anzan.letsfreckle.com/timer' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

(about:blank:1)

I noticed that this was no longer working yesterday around 4:00 MTS.

**Comment by madrobby** [comment]
Thomas from Freckle here. Thanks for reporting. We'll try to detect this an make an exception.
