### ISSUE TITLE
Publishing latest version

### ISSUE THREAD

**Issue by tcannonfodder** [RobertDaleSmith/freckle-chrome-extension#5]
Hey there!

Cannon from Freckle here, could you please publish the latest version of the extension with our fix? We've had customers write into our support that it isn't working, and we want to get it fixed for them.

Thanks!
Cannon

**Comment by RobertDaleSmith** [comment]
I apologize for the delay. Update pushed. Let me know if anything goes South. I no longer have a Freckle account, so unable to login and do a full set of tests.

**Comment by RobertDaleSmith** [comment]
"May take up to 60 minutes for published changes to be live."

**Comment by tcannonfodder** [comment]
Fantastic, thanks man! :D
