### ISSUE TITLE
Window from extension is very small and difficult to use

### ISSUE THREAD

**Issue by danwagnerco** [RobertDaleSmith/freckle-chrome-extension#6]
Hey @RobertDaleSmith -- first and foremost, thank you so much for your development on this project! The Freckle extension has been wonderfully helpful.

However, since upgrading to Chrome Version 50.0.2661.102 m (with version 1.0.7 of the extension installed), the drop-down window from the extension has become small and nearly unusable when time tracking is active.

The gif below shows the window as it appears in Chrome on my Win 10 machine.

**Am I doing something wrong?**

![small-window](https://cloud.githubusercontent.com/assets/6598675/15427687/67a7b7d6-1e5c-11e6-9f52-c57b978c8402.gif)

**Comment by RobertDaleSmith** [comment]
Thanks for the heads up. I will take a look at this over the weekend and see if I can get it cleaned up. Although I still love Freckle, I no longer work for a company that uses it. So it has been a little off my radar. 

If any developers out there want to take a stab at it before I get to it, then feel free to submit a pull request.

Thanks!

**Comment by RobertDaleSmith** [comment]
Should be resolved by commit: b302f80

Ver 1.0.8 rolling out now. :)

**Comment by danwagnerco** [comment]
Yo @RobertDaleSmith -- v 1.0.8 is working like a dream!

![image](https://cloud.githubusercontent.com/assets/6598675/15689129/2865ba74-2743-11e6-858e-0873c74f7eed.png)

Thank you so much for your help on this and have a great day!

**Comment by RobertDaleSmith** [comment]
NICE!  👍  Thanks so much for letting me know both that it was broke and that it now works! 😄
